---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: prometheus
  namespace: tanzu-system
spec:
  serviceAccountName: platform-gitops-sa
  packageRef:
    refName: prometheus.tanzu.vmware.com
    versionSelection:
      constraints: 2.43.0+vmware.2-tkg.1
  values:
  - secretRef:
      name: prometheus-packages-values